export type PemegangLesenSubmodule = {
  slug: string;
  title: string;
  description: string;
  processes: string[];
};

export const pemegangLesenSubmodules: PemegangLesenSubmodule[] = [
  {
    slug: "permohonan",
    title: "Permohonan (Realtime Monitoring)",
    description:
      "Permohonan lesen, pengiktirafan, pendaftaran, kebenaran, pembayaran fee, program/pelan dan realtime monitoring.",
    processes: [
      "2.2.1 Permohonan Lesen - Baru",
      "2.2.1 Permohonan Lesen - Meminda",
      "2.2.1 Permohonan Lesen - Memperbaharui",
      "2.2.1 Permohonan Lesen - Senarai Draf Permohonan",
      "2.2.2 Pengiktirafan Pekerja - Pengiktirafan Baru",
      "2.2.2 Pengiktirafan Pekerja - Pengiktirafan Semula",
      "2.2.2 Pengiktirafan Pekerja - Penukaran Jawatan",
      "2.2.2 Pengiktirafan Pekerja - Penambahan Radas / Projektor",
      "2.2.2 Pengiktirafan Pekerja - Pembaharuan Permit Pekerja",
      "2.2.2 Pengiktirafan Pekerja - Penukaran RWMO",
      "2.2.3 Pendaftaran - Pendaftaran Model Radas",
      "2.2.3 Pendaftaran - Pendaftaran Model Bekas",
      "2.2.3 Pendaftaran - Pendaftaran SEM",
      "2.2.3 Pendaftaran - Penukaran OBTL",
      "2.2.3 Pendaftaran - Penukaran OBTP",
      "2.2.3 Pendaftaran - Pengamal Perubatan",
      "2.2.4 Kebenaran",
      "2.2.5 Pembayaran Fee - Fee Permohonan Lesen",
      "2.2.6 Program Perlindungan Sinaran",
      "2.2.7 Pelan Kecemasan",
      "2.2.8 Pelan Sekuriti",
      "2.2.9 Permohonan Pengesahan Pengecualian Akta 304",
      "2.2.10 Real-time monitoring",
    ],
  },
  {
    slug: "maklumbalas-kemaskini",
    title: "Maklumbalas & Kemaskini",
    description:
      "Maklumbalas pemilikan, penjualan, pelupusan, pemindahan, eksport, notis, pemeriksaan, laporan, dan kemaskini maklumat syarikat.",
    processes: [
      "2.3.1 Penyata Pemilikan - Bahan Radioaktif",
      "2.3.1 Penyata Pemilikan - Radas Penyinaran",
      "2.3.1 Penyata Pemilikan - Bahan Nuklear",
      "2.3.2 Penyata Penjualan - Bahan Radioaktif",
      "2.3.2 Penyata Penjualan - Radas Penyinaran",
      "2.3.2 Penyata Penjualan - Bahan Nuklear",
      "2.3.3 Maklumbalas Pelupusan - Bahan Radioaktif",
      "2.3.3 Maklumbalas Pelupusan - Bahan Nuklear",
      "2.3.4 Maklumbalas Pemindahan Bahan - Bahan Radioaktif",
      "2.3.4 Maklumbalas Pemindahan Bahan - Bahan Nuklear",
      "2.3.5 Maklumbalas Eksport - Bahan Radioaktif",
      "2.3.5 Maklumbalas Eksport - Bahan Nuklear",
      "2.3.5 Maklumbalas Eksport - Radas Penyinaran",
      "2.3.6 Maklumbalas Pembubaran Radas",
      "2.3.7 Maklumbalas Meter Tinjau",
      "2.3.8 Notis Pemberitahuan - Penyenggaraan/Pengujian Radas",
      "2.3.8 Notis Pemberitahuan - Penyenggaraan/Pengujian Bekas",
      "2.3.8 Notis Pemberitahuan - Pergerakan Bahan Radioaktif",
      "2.3.8 Notis Pemberitahuan - Pergerakan Bahan Nuklear (Perisaian)",
      "2.3.8 Notis Pemberitahuan - Kerja Nyahcemaran Peralatan Yang Tercemar",
      "2.3.8 Notis Pemberitahuan - Perkhidmatan Ujian Kebocoran",
      "2.3.9 Maklumbalas Penyenggaraan - Radas Penyinaran",
      "2.3.9 Maklumbalas Penyenggaraan - Bekas Punca",
      "2.3.10 Maklumbalas Ujian Kebocoran - Perkhidmatan Ujian Kebocoran",
      "2.3.10 Maklumbalas Ujian Kebocoran - Ujian Kebocoran Sendiri",
      "2.3.11 Maklumbalas Tamat Peminjaman",
      "2.3.12 Maklumbalas Pemeriksaan",
      "2.3.13 Maklumbalas Aduan",
      "2.3.14 Pemberhentian Pekerja",
      "2.3.15 Pemeriksaan Perubatan - Berkala",
      "2.3.15 Pemeriksaan Perubatan - Khas",
      "2.3.16 Laporan Dos",
      "2.3.17 Laporan Juruperunding",
      "2.3.18 Pemberitahuan Kerja Radiografi",
      "2.3.19 Maklumbalas Kerja Nyahcemaran Peralatan Yang Tercemar",
      "2.3.20 Maklumbalas Hapus Guna Bilik Dedahan",
      "2.3.21 Maklumbalas Borang Inventori Tahunan dan Rekod Sisa Radioaktif - Jadual Keempat",
      "2.3.21 Maklumbalas Borang Inventori Tahunan dan Rekod Sisa Radioaktif - Jadual Kelima",
      "2.3.22 Rekod Latihan (Agensi Latihan)",
      "2.3.23 Kemaskini Maklumat - Alamat Lain-lain Premis",
      "2.3.23 Kemaskini Maklumat - Hapus Guna Penstoran",
      "2.3.23 Kemaskini Maklumat - Perkongsian Tempat Penstoran",
      "2.3.23 Kemaskini Maklumat - Penukaran Nama Syarikat",
    ],
  },
  {
    slug: "pemantauan-radiologi",
    title: "Pemantauan Radiologi",
    description:
      "Syarikat key-in data permonitoran alam sekitar meliputi pra permonitoran, permohonan, permonitoran sampel, akaun pengguna dan laporan.",
    processes: [
      "2.4.2 Pra Permonitoran - Maklumat Syarikat Diselenggara",
      "2.4.2 Pra Permonitoran - Pendaftaran Baru",
      "2.4.2 Pra Permonitoran - Senarai Syarikat Permonitoran Radiologi",
      "2.4.2 Pra Permonitoran - Maklumat Lokasi/Tapak",
      "2.4.2 Pra Permonitoran - Maklumat Persampelan",
      "2.4.3 Permohonan (Syarikat Berlesen) - Permohonan Baru",
      "2.4.3 Permohonan (Syarikat Berlesen) - Draf Permohonan",
      "2.4.3 Permohonan (Syarikat Berlesen) - Semak Semula",
      "2.4.3 Permohonan (Syarikat Berlesen) - Penambahan/Pengurangan Lokasi/Tapak",
      "2.4.3 Permohonan (Syarikat Berlesen) - Status Permohonan",
      "2.4.3 Permohonan (Syarikat Tidak Berlesen) - Permohonan Baru",
      "2.4.4 Permonitoran Radiologi (Syarikat Berlesen) - Senarai Syarikat",
      "2.4.4 Permonitoran Radiologi (Syarikat Berlesen) - Permonitoran Sampel",
      "2.4.4 Permonitoran Radiologi (Syarikat Tidak Berlesen) - Permonitoran Sampel",
      "2.4.5 Akaun Pengguna - Maklumat Syarikat",
      "2.4.5 Akaun Pengguna - Senarai Syarikat Diselenggara",
      "2.4.5 Akaun Pengguna - Syarikat Pra Permonitoran",
      "2.4.5 Akaun Pengguna - Syarikat Berlesen",
      "2.4.5 Akaun Pengguna - Syarikat Tidak Berlesen",
      "2.4.6 Laporan",
    ],
  },
  {
    slug: "akaun-pengguna",
    title: "Akaun Pengguna",
    description:
      "Pengurusan profil syarikat, senarai aset/radas, program/pelan, laporan juruperunding, pemeriksaan dan salinan sijil lesen.",
    processes: [
      "2.5.1 Maklumat Syarikat",
      "2.5.2 Senarai Alamat",
      "2.5.3 Senarai Pekerja",
      "2.5.4 Senarai Pengamal Perubatan",
      "2.5.5 Meter Tinjau",
      "2.5.6 Bahan Radioaktif",
      "2.5.7 Bahan Nuklear",
      "2.5.8 Radas Penyinaran",
      "2.5.9 Radas Khidmat Senggara",
      "2.5.10 Radas Penyinaran Pengkelasan Semula",
      "2.5.11 Program Perlindungan Sinaran",
      "2.5.12 Pelan Kecemasan",
      "2.5.13 Pelan Sekuriti",
      "2.5.14 Senarai Laporan Juruperunding",
      "2.5.15 Maklumat Pemeriksaan",
      "2.5.16 Salinan Sijil Lesen",
    ],
  },
];

export function getPemegangLesenSubmoduleBySlug(slug: string) {
  return pemegangLesenSubmodules.find((submodule) => submodule.slug === slug);
}
