export type KawalseliaSubmodule = {
  number: number;
  slug: string;
  title: string;
  description: string;
  processes: string[];
  mockFocus: string;
};

export const kawalseliaSubmodules: KawalseliaSubmodule[] = [
  {
    number: 1,
    slug: "permohonan-pengesahan-peralatan-pengecualian-akta-304",
    title: "Permohonan Pengesahan Peralatan Di Bawah Pengecualian Akta 304",
    description:
      "Pengurusan permohonan pengesahan peralatan di bawah pengecualian Akta 304.",
    processes: ["Permohonan Baru", "Semakan Dokumen", "Status Semua Permohonan"],
    mockFocus: "Pengesahan Peralatan",
  },
  {
    number: 2,
    slug: "permohonan-kebenaran",
    title: "Permohonan Kebenaran",
    description:
      "Pengurusan permohonan kebenaran termasuk syarikat bermasalah dan kebenaran pelupusan.",
    processes: [
      "Permohonan Syarikat Bermasalah (P/KP)",
      "Senarai Permohonan (PS)",
      "Senarai Permohonan (KU)",
      "Senarai Lulus (Slip)",
      "Senarai Lulus/Gagal (Slip)",
      "Status Semua Permohonan",
      "Kebenaran Pelupusan (Penangkap Kilat, NORM, Sekolah, Awam)",
    ],
    mockFocus: "Kebenaran",
  },
  {
    number: 3,
    slug: "notis-pemberitahuan",
    title: "Notis Pemberitahuan",
    description: "Pengurusan notis pemberitahuan operasi, pergerakan, dan perkhidmatan teknikal.",
    processes: [
      "Penyenggaraan/Pengujian Radas",
      "Penyenggaraan/Pengujian Bekas",
      "Pergerakan Bahan Radioaktif",
      "Pergerakan Bahan Nuklear (Perisaian)",
      "Perkongsian Penstoran Sementara",
      "Kerja Nyahcemaran Peralatan Yang Tercemar",
      "Perkhidmatan Ujian Kebocoran",
    ],
    mockFocus: "Notis",
  },
  {
    number: 4,
    slug: "pengesahan-maklumbalas",
    title: "Pengesahan Maklumbalas",
    description:
      "Pengesahan pelbagai jenis maklumbalas pemilikan, pemindahan, eksport, pemasangan, dan laporan.",
    processes: [
      "Penyata Pemilikan",
      "Penyata Penjualan",
      "Maklumbalas Pelupusan",
      "Maklumbalas Pemindahan Bahan",
      "Maklumbalas Eksport Bahan",
      "Maklumbalas Pembubaran Radas",
      "Maklumbalas Eksport Radas",
      "Maklumbalas Pindah Milik Bahan",
      "Maklumbalas Pindah Milik Radas",
      "Maklumbalas Meter Tinjau",
      "Maklumbalas Penyenggaraan",
      "Maklumbalas Pemasangan",
      "Maklumbalas Ujian Kebocoran",
      "Maklumbalas Tamat Peminjaman",
      "Pemeriksaan Perubatan",
      "Laporan Juruperunding",
      "Laporan PPB",
      "Maklumbalas Pemberhentian Pekerja",
      "Maklumbalas Kerja Nyahcemaran Peralatan Yang Tercemar",
      "Maklumbalas Hapus Guna Bilik Dedahan",
      "Maklumbalas Inventori Sisa (Jadual Ke-4)",
      "Maklumbalas Rekod Sisa (Jadual Ke-5)",
    ],
    mockFocus: "Maklumbalas",
  },
  {
    number: 5,
    slug: "permohonan-pelupusan-bukan-pemegang-lesen",
    title: "Permohonan Pelupusan Bukan Pemegang Lesen",
    description:
      "Urusan permohonan pelupusan untuk bukan pemegang lesen dari permohonan hingga keputusan.",
    processes: [
      "Permohonan Baru (PS)",
      "Senarai Permohonan (KU)",
      "Senarai Lulus/Gagal (Slip)",
      "Status Semua Permohonan",
    ],
    mockFocus: "Pelupusan",
  },
  {
    number: 6,
    slug: "maklumbalas-pelupusan-bukan-pemegang-lesen",
    title: "Maklumbalas Pelupusan Bukan Pemegang Lesen",
    description: "Pengesahan dan jejak maklumbalas bagi pelupusan bukan pemegang lesen.",
    processes: ["Senarai Maklumbalas", "Verifikasi Pegawai", "Status Maklumbalas"],
    mockFocus: "Maklumbalas Pelupusan",
  },
  {
    number: 7,
    slug: "status-penerimaan-buku-rekod-pekerja",
    title: "Status Penerimaan Buku Rekod Pekerja",
    description: "Pemantauan status penerimaan buku rekod pekerja sinaran.",
    processes: ["Senarai Buku Rekod", "Status Penerimaan", "Pengesahan Penerimaan"],
    mockFocus: "Buku Rekod",
  },
  {
    number: 8,
    slug: "laporan-dos",
    title: "Laporan Dos",
    description: "Pengurusan laporan dos pekerja dan pemantauan pematuhan.",
    processes: ["Muat Naik Laporan", "Semakan Laporan", "Status Pematuhan"],
    mockFocus: "Laporan Dos",
  },
  {
    number: 9,
    slug: "aduan",
    title: "Aduan",
    description: "Pengurusan aduan, maklumbalas kemalangan, dan status keseluruhan aduan.",
    processes: [
      "Pengarah, Timbalan Pengarah, Ketua Unit",
      "Pegawai Bertugas",
      "Pegawai Bertindak Balas",
      "Maklumbalas Aduan Kemalangan",
      "Status Semua Aduan",
    ],
    mockFocus: "Aduan",
  },
  {
    number: 10,
    slug: "pemeriksaan",
    title: "Pemeriksaan",
    description: "Kitaran penuh pemeriksaan bermula dari pra-pemeriksaan hingga verifikasi tapak.",
    processes: [
      "Pra Pemeriksaan",
      "Jadual Pemeriksaan",
      "Pemberitahuan Kerja Radiografi",
      "Pemeriksaan Baru",
      "Maklumbalas Pemeriksaan",
      "Rekod Pemeriksaan",
      "Janaan Surat Temujanji Pemeriksaan",
      "Verifikasi Tapak",
    ],
    mockFocus: "Pemeriksaan",
  },
  {
    number: 11,
    slug: "butiran-kesalahan",
    title: "Butiran Kesalahan",
    description: "Pengurusan butiran kesalahan syarikat dan pekerja sinaran selepas siasatan.",
    processes: [
      "Senarai Butiran Kesalahan Syarikat",
      "Senarai Pekerja Sinaran",
      "Pengesahan Pengarah",
      "Kemaskini Rekod Kesalahan Pekerja Sinaran Selepas Siasatan",
    ],
    mockFocus: "Kesalahan",
  },
  {
    number: 12,
    slug: "laporan-prestasi",
    title: "Laporan Prestasi",
    description: "Paparan dan semakan laporan prestasi kawalselia.",
    processes: ["Laporan Bulanan", "Laporan Suku Tahunan", "Analisis Prestasi"],
    mockFocus: "Prestasi",
  },
  {
    number: 13,
    slug: "sewa-pajak",
    title: "Sewa Pajak",
    description: "Pengurusan sewa pajak dan laporan berkaitan.",
    processes: ["Sewa Pajak", "Laporan"],
    mockFocus: "Sewa Pajak",
  },
  {
    number: 14,
    slug: "kemaskini-data-pemilikan",
    title: "Kemaskini Data Pemilikan",
    description: "Kemaskini data pemilikan untuk bahan radioaktif dan radas penyinaran.",
    processes: ["Bahan Radioaktif", "Radas Penyinaran"],
    mockFocus: "Pemilikan",
  },
  {
    number: 15,
    slug: "paparan-kemaskini-maklumbalas-pemilikan-bahan-radioaktif",
    title: "Paparan Kemaskini/Maklumbalas Pemilikan Bahan Radioaktif",
    description: "Paparan kemaskini pemilikan bahan radioaktif untuk urusan pulang ke penjual dan pindah milik.",
    processes: ["Pulang Ke Penjual", "Pindah Milik"],
    mockFocus: "Bahan Radioaktif",
  },
  {
    number: 16,
    slug: "paparan-kemaskini-maklumbalas-pemilikan-bahan-nuklear",
    title: "Paparan Kemaskini/Maklumbalas Pemilikan Bahan Nuklear",
    description: "Paparan kemaskini pemilikan bahan nuklear untuk urusan pulang ke penjual dan pindah milik.",
    processes: ["Pulang Ke Penjual", "Pindah Milik"],
    mockFocus: "Bahan Nuklear",
  },
  {
    number: 17,
    slug: "paparan-kemaskini-maklumbalas-pemilikan-radas",
    title: "Paparan Kemaskini/Maklumbalas Pemilikan Radas",
    description: "Paparan kemaskini pemilikan radas termasuk pindah milik, eksport, dan pembubaran.",
    processes: [
      "Pulang Ke Penjual",
      "Pindah Milik (Tidak Melibatkan SEM)",
      "Pindah Milik (SEM)",
      "Eksport Ke Luar Negara",
      "Pembubaran",
    ],
    mockFocus: "Radas",
  },
  {
    number: 18,
    slug: "paparan-peminjaman",
    title: "Paparan Peminjaman",
    description: "Paparan peminjaman untuk bahan radioaktif, radas penyinaran, dan meter tinjau.",
    processes: ["Bahan Radioaktif", "Radas Penyinaran", "Meter Tinjau"],
    mockFocus: "Peminjaman",
  },
];

export function getKawalseliaSubmoduleBySlug(slug: string) {
  return kawalseliaSubmodules.find((submodule) => submodule.slug === slug);
}
